DROP TABLE OPT_OUT;

COMMIT;

CREATE TABLE OPT_OUT(

FIRST_NAME NVARCHAR(70),

MIDDLE_NAME NVARCHAR(70),

LAST_NAME NVARCHAR(70),

FIRST_NAME_PERSON_COMPLETING_FORM NVARCHAR(70),

LAST_NAME_PERSON_COMPLETING_FORM NVARCHAR(70),

PHONE_NUMBER_PERSON_COMPLETING_FORM NVARCHAR(15),

RELATIONSHIP_PERSON_COMPLETING_FORM NVARCHAR(30),

GENDER NVARCHAR(15),

DATE_OF_BIRTH DATE,

PREVIOUS_FIRST_NAME NVARCHAR(70),

PREVIOUS_LAST_NAME NVARCHAR(70),

ADDRESS NVARCHAR(100),

APARTMENT_NUMBER NVARCHAR(100),

CITY NVARCHAR(40),

STATE NVARCHAR(40),

ZIP_CODE NVARCHAR(15),

MEMBER_HEALTH_PLAN NVARCHAR(10),

HEALTH_PLAN_NAME NVARCHAR(50),

GROUP_ID NVARCHAR(15),

SUBSCRIBER_ID NVARCHAR(15),

EMAIL NVARCHAR(70),

MAIN_PHONE_NUMBER NVARCHAR(15),

ALTERNATE_PHONE_NUMBER NVARCHAR(15)

);

COMMIT;